<?php
/**
 * Magento Xib|payments Payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   F500
 * @package    F500_Xibpayments
 * @author     Ramon de la Fuente, <ramon@future500.nl>
 * @copyright  Copyright (c) 2009 Future500 BV, the Netherlands
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$banks = $this->getBanks();
$_code = $this->getMethodCode();


$options = $this->getEnabledOptions();

$selected_option = $this->getInfoData('xibpayments_option');
$selected_bank = $this->getInfoData('xibpayments_bank');

if ( in_array('', $options) ) {
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Xib|payments, our payment processor, after you place the order.') ?>
        </li>
    </ul>
</fieldset>
<?
} else {
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>">
    <?php
        foreach ( $options as $option ) {
    ?>
        <li>
            <?php 
                echo '<label onclick="document.getElementById(\'p_method_xibpayments\').checked = true;payment.switchMethod(\'xibpayments\');"><input type="radio" id="p_method_xibpayments_option_' . $option . '" name="payment[xibpayments_option]" value="' . $option . '" ' . ( ($selected_option == $option)||(count($options)==1) ? 'checked="checked"' : '') . '> ' . ( '' !== ($optiontitle = $this->getOptionTitle($option)) ? $optiontitle : $this->__($option)) . '</label>'; 
                if ( $option == 'ideal' ) {
                    $result = '<select  style="margin-left: 10px;" name="payment[xibpayments_bank]" onchange="document.getElementById(\'p_method_xibpayments\').checked = true;document.getElementById(\'p_method_xibpayments_option_' . $option . '\').checked = true; payment.switchMethod(\'xibpayments\');">';
                    $result .= '<option value="">' . $this->__('Select your bank') . '</option>';
                    foreach ( $banks as $bankcode => $bankname ) {
                        if ( $bankcode === '-' ) {
                            $result .= '<option value="">------' . $this->__('Additional banks') . '------</option>';
                        } else {
                            $result .= '<option value="' . $bankcode . '" ' . ( $selected_bank == $bankcode ? 'selected="selected"' : '' ) . '>' . $this->__($bankname) . '</option>';
                        }
                    }            
                    $result .= '</select>';
                    echo  $result;
                }
            ?>
        </li>
    <?php            
        }
    ?>        
    </ul>
</fieldset>
<?
}
?>
